spring:
  servlet:
    #文件操作参数配置
    multipart:
      max-file-size: 10MB      #单个文件的最大限制
      max-request-size: 30MB   #设置上传文件的总大小
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hj_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 12345678

# MinIO 配置
minio:
  endpoint: http://172.16.112.132:9000      # MinIO服务地址
  fileHost: http://172.16.112.132:9000      # 文件地址host
  bucketName: hj-shop                      # 存储桶bucket名称
  accessKey: admin                         # 用户名
  secretKey: 12345678                    # 密码
  imgSize: 1024                           # 图片大小限制，单位：m
  fileSize: 1024                          # 文件大小限制，单位：m